# -*- coding: utf-8 -*-
"""spam_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfBTKU8eoIaWZRf9-Z2WSSgwBxkzUygg

# Spam Detector
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

"""## Retrieve the Data

The data is located at [https://static.bc-edx.com/ai/ail-v-1-0/m13/challenge/spam-data.csv](https://static.bc-edx.com/ai/ail-v-1-0/m13/challenge/spam-data.csv)

Dataset Source: [UCI Machine Learning Library](https://archive.ics.uci.edu/dataset/94/spambase)

Import the data using Pandas. Display the resulting DataFrame to confirm the import was successful.
"""

# Import the data
data = pd.read_csv("https://static.bc-edx.com/ai/ail-v-1-0/m13/challenge/spam-data.csv")
data.head()

"""## Predict Model Performance

You will be creating and comparing two models on this data: a Logistic Regression, and a Random Forests Classifier. Before you create, fit, and score the models, make a prediction as to which model you think will perform better. You do not need to be correct!

Write down your prediction in the designated cells in your Jupyter Notebook, and provide justification for your educated guess.

*Replace the text in this markdown cell with your predictions, and be sure to provide justification for your guess.*

## Split the Data into Training and Testing Sets
"""

# Create the labels set `y` and features DataFrame `X`
X = data.drop(columns="spam")
y = data["spam"]

# Check the balance of the labels variable (`y`) by using the `value_counts` function.
y.value_counts()

# Split the data into X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
X_train.head()

"""## Scale the Features

Use the `StandardScaler` to scale the features data. Remember that only `X_train` and `X_test` DataFrames should be scaled.
"""

from sklearn.preprocessing import StandardScaler

# Create the StandardScaler instance
spammail_scaler = StandardScaler()

# Fit the Standard Scaler with the training data
X_scaler = spammail_scaler.fit(X_train)

# Scale the training data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

"""## Create and Fit a Logistic Regression Model

Create a Logistic Regression model, fit it to the training data, make predictions with the testing data, and print the model's accuracy score. Use a `random_state` of `1`.
"""

# Create and fit a Logistic Regression model
from sklearn.linear_model import LogisticRegression
reg_model = LogisticRegression(random_state=0)
reg_model.fit(X_train_scaled, y_train)

# Make and save testing predictions with the trained Logistic Regression model using the test data
pred_test = reg_model.predict(X_test_scaled)
# Review the predictions
pred_test

# Calculate the accuracy score by evaluating `y_test` vs. `testing_predictions`.
accuracy_score(y_test, pred_test)

"""## Create and Fit a Random Forest Classifier Model

Create a Random Forest Classifier model, fit it to the training data, make predictions with the testing data, and print the model's accuracy score. Use a `random_state` of `1`.
"""

# Create and fit a Random Forest Classifier model
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(random_state=0)
rf_classifier.fit(X_train_scaled, y_train)

# Make and save testing predictions with the trained Random Forest Classifier model using the test data
pred_test = rf_classifier.predict(X_test_scaled)
# Review the predictions
pred_test

# Review the predictions

# Calculate the accuracy score by evaluating `y_test` vs. `testing_predictions`.
accuracy_score(y_test, pred_test)

"""## Evaluate the Models

Which model performed better? How does that compare to your prediction? Write down your results and thoughts in the following markdown cell.

The random forest classifier performed better with an accuracy score of 94.7% over the logistic regression model's 90.3% accuracy score
"""

